version: '3'

services:
  cproject-builder:
    image: cproject-builder:latest
    platform: linux/amd64
    command: /bin/bash
    working_dir: /builder/mnt
    volumes:
      - .:/builder/mnt
    stdin_open: true
    tty: true
