- name: Update DNS
  hosts: master
  gather_facts: false
  connection: local
  become: true
  tasks:
    - name: Update DNS
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "{{ item }}"
        insertbefore: '^nameserver'
      loop:
        - nameserver 114.114.114.114
        - nameserver 8.8.8.8
    - name: Update worker hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      loop:
        - 172.23.204.223  worker1
        - 172.23.198.65   worker2
        - 172.23.206.56   worker3

- name: SSH Connection Config
  hosts: worker
  gather_facts: false
  connection: local
  tasks:
    - name: Install sshpass
      run_once: true
      ansible.builtin.apt:
        name: sshpass
    - name: SSH Connection Config
      changed_when: false
      ansible.builtin.shell: |
        ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
        sshpass -p'vagrant' ssh-copy-id vagrant@{{ inventory_hostname }}
