- name: Update DNS
  lineinfile:
    path: /etc/resolv.conf
    line: "{{ item }}"
    insertbefore: '^nameserver'
  loop:
  - nameserver 114.114.114.114
  - nameserver 8.8.8.8

- name: Update worker hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_host }} {{ inventory_hostname }}"

- name: Install sshpass
  apt:
    name: sshpass

- name: SSH Connection Config
  changed_when: false
  shell: |
    ssh-keyscan {{ inventory_hostname }} >> ~/.ssh/known_hosts
    sshpass -p'vagrant' ssh-copy-id vagrant@{{ inventory_hostname }}
