name: Build and Deploy
on: [push]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
      - name: Build
        run: |
          npm add -g pnpm
          cd frontend/react/product_stock_list
          pnpm i
          pnpm build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/react/product_stock_list
          cname: eraserandrain.github.io/product_stock_list
          enable_jekyll: true
